apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-gha
type: Opaque
stringData:
  POSTGRESQL_DATABASE: guestbook-gha
  POSTGRESQL_USERNAME: guest-gha
  POSTGRESQL_PASSWORD: ocp123-gha
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-gha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
    storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-gha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-gha
  template:
    metadata:
      labels:
        app: postgres-gha
    spec:
      containers:
        - name: postgres-gha
          image: docker.io/bitnamilegacy/postgresql:16.6.0-debian-12-r2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-gha
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-gha
                  key: POSTGRESQL_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-gha
                  key: POSTGRESQL_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc-gha
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-gha
spec:
  selector:
    app: postgres-gha
  ports:
    - name: tcp-5432
      port: 5432
      targetPort: 5432

